datasets:
  raw:
    googlesearch:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/google_search_data.csv
      driver_params: {}
  
    manufacturerlist:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
      driver_params: {}
      
    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales_data.csv
      driver_params: {}
    
    socialmedia:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/social_media_data.csv
      driver_params: {}
    
    theme:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_list.csv
      driver_params: {}
      
    themeproduct:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_product_list.csv
      driver_params: {}
      
  cleaned:
      googlesearch:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/googlesearch.parquet
          driver_params: {}
      manufacturerlist:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/manufacturerlist.parquet
          driver_params: {}
      sales:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/sales.parquet
          driver_params: {}
      socialmedia:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/socialmedia.parquet
          driver_params: {}
      theme:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/theme.parquet
          driver_params: {}
      themeproduct:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/themeproduct.parquet
          driver_params: {}
      merged_data:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/merged_data.parquet
          driver_params: {}
      social_google_sales_data:
          type: ds
          format: parquet
          uri: ${core.data_base_path}/cleaned/social_google_sales_data.parquet
          driver_params: {}
  processed:
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales.parquet
      driver_params: {}
  train:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/features.parquet
        driver_params: {}
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/target.parquet
        driver_params: {}
  test:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/features.parquet
        driver_params: {}
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/target.parquet
        driver_params: {}
